# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      target_env: 
        description: 'Target github environment to use'
        default: 'dev_env'
        required: true
      kubectl_version:
        description: 'Version of kubectl to be installed'
        default: '1.19.9'
        required: true
      # Use following command to generate base64 code:
      #   cat <<EOF | base64 | tr -d '\n' | xargs echo
      #   <your_autoscalegroups_yaml>
      #   EOF
      auto_scale_groups:
        description: |
          The auto scale groups defined in yaml to apply given as a string from base64 encoding.
          See the comments in .github/workflows/manual.yml for how to get a base64 encoded yaml.
          If this is set to empty, the nodeautoscaler/deploy/auto-scale-groups-configmap.yml in repo will be used.
        default: ''
        required: false
      all_peers_ip:
        description: |
          The private IPs of all nodes running keepalived talked to AWS separated by comma.
          For example, "10.0.0.1,10.0.0.2"
        default: ''
        required: true
      eip_alloc_id:
        description: |
          The allocation ID of elastic IP in AWS used as the virtual IP in keepalived.
          If this is set to empty, the value of secret EIP_ALLOC_ID in the input env
          set by target_env will be used
        default: ''
        required: false
      kube_config:
        description: |
          A base64 encoded kubeconfig file content which is used to apply workloads.
          If this is set to empty, the value of secret KUBE_CONFIG in the input env
          set by target_env will be used
        default: ''
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy workloads
  deploy_workloads:
    # Use dev environment
    environment: ${{ github.event.inputs.target_env }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variables
    env:
      AUTO_SCALE_GROUPS: ${{ github.event.inputs.auto_scale_groups }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup kubectl with input kubeconfig
      uses: ThomasKliszowski/setup-kubectl@v1
      if: ${{ github.event.inputs.kube_config != '' }}
      with:
        # Base64 encoded kube config
        kube-config: ${{ github.event.inputs.kube_config }}
        # Kube version used to download kubectl executable, defaults to latest
        kube-version: ${{ github.event.inputs.kubectl_version }}
    # Install kubectl tool
    - name: Setup kubectl with empty input kubeconfig
      uses: ThomasKliszowski/setup-kubectl@v1
      if: ${{ github.event.inputs.kube_config == '' }}
      with:
        # Base64 encoded kube config
        kube-config: ${{ secrets.KUBE_CONFIG }}
        # Kube version used to download kubectl executable, defaults to latest
        kube-version: ${{ github.event.inputs.kubectl_version }}
    # Check installed kubectl
    - name: Check installed kubectl
      run: |
        kubectl version
    # Check configured kubeconfig
    - name: Check kubeconfig
      run: |
        kubectl config view
    # Checkout local repo
    - name: Checkout
      uses: actions/checkout@v2.3.4
    # Replace ConfigMap of auto scale groups with input value
    - name: Generate configmap with input auto scale groups
      if: ${{ env.AUTO_SCALE_GROUPS != '' }}
      run: |
        echo "********** Got input auto scale groups ***********"
        echo ${AUTO_SCALE_GROUPS} | base64 -d | tee autoscalegroups.yaml
        echo "********** Generate configmap ************"
        kubectl apply cm auto-scale-groups -n node-auto-scaler --from-file=autoscalegroups.yaml \
           --dry-run=client -o yaml
    # Apply configmap in the repo
    - name: Create configmap of auto scale groups
      if: ${{ env.AUTO_SCALE_GROUPS == '' }}
      run: |
        echo "Create configmap"
        kubectl apply -f ${GITHUB_WORKSPACE}/nodeautoscaler/deploy/auto-scale-groups-configmap.yml \
          --dry-run=client -o yaml
